### ISSUE TITLE
self.device=device

### ISSUE THREAD

**Issue by jiayalu123** [ShimShim46/HFT-CNN#7]
执行命令的时候报错，报错内容如下：
Traceback (most recent call last):
  File "train.py", line 207, in <module>
    main()
  File "train.py", line 166, in main
    y_pred = train_problem(current_depth="flat", upper_depth=None, class_num=len(learning_categories), fine_tuning=fine_tuning, embedding_weight=embedding_weight, input_data=input_network_data, model_type=model_type, learning_categories=learning_categories)
  File "train.py", line 40, in train_problem
    network_output = cnn_train.main(params)
  File "E:\▒▒▒▒▒\▒▒▒▒▒▒▒\▒▒▒ܹ▒▒▒\HFT-CNN-master\cnn_train.py", line 121, in main
    updater = MyUpdater(train_iter, optimizer, params["output_dimensions"], device=params["gpu"])
  File "E:\▒▒▒▒▒\▒▒▒▒▒▒▒\▒▒▒ܹ▒▒▒\HFT-CNN-master\MyUpdater.py", line 36, in __init__
    self.device = device
AttributeError: can't set attribute

**Comment by qinglongheu** [comment]
兄弟，你解决了吗？？
